# Generated by Django 3.2.3 on 2021-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='name')),
                ('user_surname', models.CharField(max_length=200, verbose_name='surname')),
                ('user_email', models.EmailField(max_length=45, verbose_name='email')),
                ('user_password', models.CharField(max_length=25, verbose_name='password')),
                ('user_tell', models.IntegerField(verbose_name='tell')),
                ('user_birthday', models.DateField(verbose_name='birthday')),
                ('user_booking', models.DateField(verbose_name='booking')),
                ('user_gender', models.CharField(max_length=25, verbose_name='sex')),
            ],
        ),
    ]
